// <auto-generated />
namespace MSBandHealth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddSkinTemp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSkinTemp));
        
        string IMigrationMetadata.Id
        {
            get { return "201504131617269_AddSkinTemp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
